name: Deploy

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Setup key
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
#      - run: set -eu
#      - run: mkdir "$HOME/.ssh"
#      - run: echo "${{ secrets.SSH_KEY }}" > "$HOME/.ssh/key"
#      - run: chmod 600 "$HOME/.ssh/key"
      # Build
      - run: cd client && npm ci
      - run: cd ..
      - run: npm run client:build
      # Deploy
      - run: cd client && cd build && rsync --archive --compress --delete . root@84.38.181.170:/root/elbrus-sn/client/build
